export const DOCUMENT_SCHEMA_TYPES = {
  footer: 'footerDocumentType',
  inlineGalleryModule: 'inlineGalleryModuleDocumentType',
  howItWorksModule: 'howItWorksModuleDocumentType',
  processModule: 'processModuleDocumentType',
  heroModule: 'heroModuleDocumentType',
  halfHeroModule: 'halfHeroModuleDocumentType',
  studioModule: 'studioModuleDocumentType',
  bookModule: 'bookModuleDocumentType',
  countersModule: 'countersModuleDocumentType',
  brandsModule: 'brandsModuleDocumentType',
  readyToStartModule: 'readyToStartModuleDocumentType',
  reasonsModule: 'reasonsModuleDocumentType',
  quotesModule: 'quotesModuleDocumentType',
  reviewsModule: 'reviewsModuleDocumentType',
  textWithImageModule: 'textWithImageModuleDocumentType',
  servicesModule: 'servicesModuleDocumentType',
  cardsModule: 'cardsModuleDocumentType',
  teamModule: 'teamModuleDocumentType',
  scrollGalleryModule: 'scrollGalleryModuleDocumentType',
  pageLayout: 'pageLayoutDocumentType',
  imageModule: 'imageModuleDocumentType',
  parallaxImagesModule: 'parallaxImagesModuleDocumentType',
  brand: 'brandDocumentType',
  quote: 'quoteDocumentType',
  review: 'reviewDocumentType',
  clientSecretPage: 'clientSecretPageDocumentType',
  clientSecretPageVersion: 'clientSecretPageVersionDocumentType'
} as const;

export const OBJECT_SCHEMA_TYPES = {
  imagePair: 'imagePairObjectType',
  link: 'linkObjectType',
  cta: 'ctaObjectType',
  contact: 'contactObjectType',
  card: 'cardObjectType',
  counter: 'counterObjectType',
  howItWorksStep: 'howItWorksStepObjectType',
  processStep: 'processStepObjectType',
  teamMember: 'teamMemberObjectType',
  scrollGalleryImage: 'scrollGalleryImageObjectType'
} as const;
