export const DOCUMENT_SCHEMA_TYPES = {
  footer: 'footerDocumentType',
  policyPage: 'policyPageDocumentType',
  topbar: 'topbarDocumentType',
  maintananceScreen: 'maintananceScreenDocumentType',
  inlineGalleryModule: 'inlineGalleryModuleDocumentType',
  howItWorksModule: 'howItWorksModuleDocumentType',
  processModule: 'processModuleDocumentType',
  heroModule: 'heroModuleDocumentType',
  halfHeroModule: 'halfHeroModuleDocumentType',
  studioModule: 'studioModuleDocumentType',
  bookModule: 'bookModuleDocumentType',
  countersModule: 'countersModuleDocumentType',
  brandsModule: 'brandsModuleDocumentType',
  readyToStartModule: 'readyToStartModuleDocumentType',
  quotesModule: 'quotesModuleDocumentType',
  reviewsModule: 'reviewsModuleDocumentType',
  textWithImageModule: 'textWithImageModuleDocumentType',
  listWithImageModule: 'listWithImageModuleDocumentType',
  servicesModule: 'servicesModuleDocumentType',
  cardsModule: 'cardsModuleDocumentType',
  teamModule: 'teamModuleDocumentType',
  scrollGalleryModule: 'scrollGalleryModuleDocumentType',
  pageLayout: 'pageLayoutDocumentType',
  imageModule: 'imageModuleDocumentType',
  parallaxImagesModule: 'parallaxImagesModuleDocumentType',
  brand: 'brandDocumentType',
  quote: 'quoteDocumentType',
  review: 'reviewDocumentType',
  formaImageAsset: 'formaImageAssetDocumentType',
  forma360Asset: 'forma360AssetDocumentType',
  mediaTagAsset: 'mediaTagAssetDocumentType',
  formaVideoAsset: 'formaVideoAssetDocumentType',
  contactUsModule: 'contactUsModuleDocumentType',
  clientSecretPage: 'clientSecretPageDocumentType',
  clientSecretPageVersion: 'clientSecretPageVersionDocumentType'
} as const;

export const OBJECT_SCHEMA_TYPES = {
  service: 'serviceObjectType',
  pageMetadata: 'pageMetadataObjectType',
  imagePair: 'imagePairObjectType',
  link: 'linkObjectType',
  forma360Instance: 'forma360InstanceObjectType',
  formaImageInstance: 'formaImageInstanceObjectType',
  formaMediaInstance: 'formaMediaInstanceObjectType',
  cta: 'ctaObjectType',
  contact: 'contactObjectType',
  card: 'cardObjectType',
  counter: 'counterObjectType',
  howItWorksStep: 'howItWorksStepObjectType',
  processStep: 'processStepObjectType',
  teamMember: 'teamMemberObjectType',
  scrollGalleryImage: 'scrollGalleryImageObjectType',
  listTextItem: 'listTextItemObjectType',
  spacing: 'spacingObjectType'
} as const;

export const FORMA_MEDIA_SELECT_PROPS = {
  formaMediaType: 'formaMedia.formaMedia._type',
  formaImageClientName: 'formaMedia.formaMedia.clientName',
  formaVideoClientName: 'formaMedia.formaMedia.clientName',
  formaImageTitle: 'formaMedia.formaMedia.imageTitle',
  formaVideoTitle: 'formaMedia.formaMedia.videoTitle',
  formaMediaOverrideAltText: 'formaMedia.overrideAltText',
  formaMediaImage: 'formaMedia.formaMedia.image',
  formaMediaVideoThumbnail: 'formaMedia.formaMedia.thumbnail'
};
